#Use an official Node.js runtime as a parent image
FROM node:18-alpine

#Qual pasta vamos trabalhar
WORKDIR /usr/src/app

#Copiar o arquivo dentro da pasta app
COPY package*.json ./

#Instalar as dependências lidas no package.json
RUN npm install

#Copy the rest of the application code to the working directory
COPY . .

CMD ["npm", "run", "dev"]
#Expor a porta 3000, porta da aplicação
EXPOSE 8080